using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using InvoiceService;

namespace UnitTests
{
    [TestClass]
    class InvoiceTest
    {
        [TestMethod]
        public void Download()
        {
            
            InvoiceService.Business business = new InvoiceService.Business()
            {
                LogoRootPath = "~//Content//Assets//Images//merge.png",
                CompanyName = "Merge Group (Pty) Ltd",
                EmailAddress = "info@mergemedia.co.za",
                WebsiteAddress = "www.mergemedia.co.za",
                PhoneNumber = "031 100 8096",
                PhysicalAddress = "16 Rosedale Place, Kloof",
                BankAccountNumber = "62746768235",
                BankBranchCode = "250 655",
                SwiftCode = "FIRNZAJJXXX",
                BankReferenceNumber = "#1561607274945",
            };
            //
            InvoiceService.Client client = new Client(
                "Roag (Mauritius)",
                "Bob",
                "0861007624",
                "info@roag.org",
                "12 Cope Road");

            List<InvoiceService.InvoiceItem> invoiceItems = new List<InvoiceItem>()
            {
                new InvoiceItem()
                {
                    Id = 1,
                    Name = "IT and development support",
                    Price = 5000,
                    Quantity = 1
                }
            };

            InvoiceService.Invoice invoice = new InvoiceService.Invoice()
            {
                Client = client,
                Business = business,
                InvoiceItems = invoiceItems,
                //
                Currency = "R",
                Title = "Invoice",
                InvoiceNumber = "1561607274945",
                Discount = 0,
                Status = "Due",
                Notes = "Thank you for your business.",
                Terms = "Sales Invoice generated by Merge Group (Pty) Ltd. Visit our website at www.Mergegroup.net for more information.",
                Date = DateTime.Now,
            };

            Generate generate = new Generate();
            byte[] pdfBytes = generate.GetInvoice(invoice);


            bool doesContainValues = true;
            bool testContainValues = false;

            if (pdfBytes == null)
            {
                testContainValues = true;
            }


            Assert.AreEqual(doesContainValues, testContainValues);
        }
    }
}
